services:
  - type: worker
    name: cobuiltPricequote-bot
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
    disk:
      name: bot-data
      mountPath: /data
      sizeGB: 1
